---
description: the vv language
keywords: vv

extensions:
  - anchor
  - d2
  - definitionlist
  - fences
  - linkify
  - footnote
  - strikethrough
  - table
  - tasklist
  - typography
  - wikilink