# NOTE: the mkdocs dependencies will need to be installed out of
# band until this whole thing gets more automated:
#
#     pip install -r mkdocs-reqs.txt
#

site_name: aperturerobotics/cli
site_url: https://cli.urfave.org/
repo_url: https://github.com/malivvan/vv/pkg/cli
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples:
      - Greet: examples/greet.md
      - Arguments: examples/arguments.md
      - Flags: examples/flags.md
      - Subcommands: examples/subcommands.md
      - Subcommands Categories: examples/subcommands-categories.md
      - Exit Codes: examples/exit-codes.md
      - Combining Short Options: examples/combining-short-options.md
      - Bash Completions: examples/bash-completions.md
      - Generated Help Text: examples/generated-help-text.md
      - Version Flag: examples/version-flag.md
      - Timestamp Flag: examples/timestamp-flag.md
      - Suggestions: examples/suggestions.md
      - Full API Example: examples/full-api-example.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: light mode
  features:
    - content.code.annotate
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - git-revision-date-localized
  - search
  - tags
# NOTE: this is the recommended configuration from
# https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
